version: "3.8"
services:
  mongo:
    image: mongo:5.0.6
    command: mongod --port ${MONGO_PORT}
    container_name: cpr-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"

  mongo2:
    image: mongo:5.0.6
    command: mongod --port ${MONGO2_PORT}
    container_name: cpr-mongo2
    restart: unless-stopped
    volumes:
      - ./db2:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:${MONGO2_PORT}:${MONGO2_PORT}"

  mongo3:
    image: mongo:5.0.6
    command: mongod --port ${MONGO3_PORT}
    container_name: cpr-mongo3
    restart: unless-stopped
    volumes:
      - ./db3:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:${MONGO3_PORT}:${MONGO3_PORT}"

  mongo4:
    image: mongo:5.0.6
    command: mongod --port ${MONGO4_PORT}
    container_name: cpr-mongo4
    restart: unless-stopped
    volumes:
      - ./db4:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:${MONGO4_PORT}:${MONGO4_PORT}"

  mongo5:
    image: mongo:5.0.6
    command: mongod --port ${MONGO5_PORT}
    container_name: cpr-mongo5
    restart: unless-stopped
    volumes:
      - ./db5:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:${MONGO5_PORT}:${MONGO5_PORT}"

  nginx:
    image: nginx:1.21.6
    restart: unless-stopped
    container_name: cpr-nginx
    volumes:
      - ./nginxDBandProxy.conf:/etc/nginx/nginx.conf:rw
    ports:
      - "3000:80"