version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    container_name: cpr-frontend
    restart: unless-stopped
    environment:
      REACT_APP_URL: ${REACT_APP_URL}

  login:
    build:
      context: ./backend/login-microservice
    container_name: cpr-login
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      EMAIL_DOMAIN: ${EMAIL_DOMAIN}
      REACT_APP_URL: ${REACT_APP_URL}

  course-manager:
    build:
      context: ./backend/course-manager-microservice
    container_name: cpr-course-manager
    restart: unless-stopped
    environment:
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  course-viewer:
    build:
      context: ./backend/course-viewer-microservice
    container_name: cpr-course-viewer
    restart: unless-stopped
    environment:
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  peer-review-teams:
    build:
      context: ./backend/peer-review-teams-microservice
    container_name: cpr-peer-review-teams
    restart: unless-stopped
    environment:
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  mongo:
    image: mongo:5.0.6
    container_name: cpr-mongo
    restart: unless-stopped
    volumes:
      - ${DATABASE_FOLDER}:/data/db
      - ${INITIALIZE_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27037:27017"

  mongo2:
    image: mongo:5.0.6
    container_name: cpr-mongo2
    restart: unless-stopped
    volumes:
      - ${DATABASE_FOLDER_2}:/data/db
      - ${INITIALIZE_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27038:27017"
  
  mongo3:
    image: mongo:5.0.6
    container_name: cpr-mongo3
    restart: unless-stopped
    volumes:
      - ${DATABASE_FOLDER_3}:/data/db
      - ${INITIALIZE_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27039:27017"
        
  mongo4:
    image: mongo:5.0.6
    container_name: cpr-mongo4
    restart: unless-stopped
    volumes:
      - ${DATABASE_FOLDER_4}:/data/db
      - ${INITIALIZE_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27040:27017"

  nginx:
    image: nginx:1.21.6
    restart: unless-stopped
    container_name: cpr-nginx
    volumes:
      - ${NGINX}:/etc/nginx/nginx.conf:rw
    ports:
      - "13125:80"