version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      args:
        URL: ${URL}
        CLIENT_ID: ${CLIENT_ID}
    container_name: cpr-frontend
    restart: unless-stopped

  login:
    build:
      context: ./backend/login-microservice
    container_name: cpr-login
    restart: unless-stopped
    volumes:
      - ./professor-list.txt:/opt/ol/wlp/output/defaultServer/professor-list.txt:rw
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

  course-manager:
    build:
      context: ./backend/course-manager-microservice
    container_name: cpr-course-manager
    restart: unless-stopped
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  course-viewer:
    build:
      context: ./backend/course-viewer-microservice
    container_name: cpr-course-viewer
    restart: unless-stopped
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  peer-review-teams:
    build:
      context: ./backend/peer-review-teams-microservice
    container_name: cpr-peer-review-teams
    restart: unless-stopped
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  professor-assignment:
    build:
      context: ./backend/professor-assignment-microservice
    container_name: cpr-professor-assignment
    restart: unless-stopped
    volumes:
      - ./assignments:/opt/ol/wlp/output/defaultServer/assignments
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  student-assignment:
    build:
      context: ./backend/student-assignment-microservice
    container_name: cpr-student-assignment
    restart: unless-stopped
    volumes:
      - ./assignments:/opt/ol/wlp/output/defaultServer/assignments
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  student-peer-review-assignment:
    build:
      context: ./backend/student-peer-review-assignment-microservice
    container_name: cpr-student-peer-review-assignment
    restart: unless-stopped
    volumes:
      - ./assignments:/opt/ol/wlp/output/defaultServer/assignments
    environment:
      URL: ${URL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO2_PORT: ${MONGO2_PORT}
      MONGO3_PORT: ${MONGO3_PORT}
      MONGO4_PORT: ${MONGO4_PORT}
      MONGO5_PORT: ${MONGO5_PORT}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  mongo:
    image: mongo:5.0.6
    command: mongod --port 27037
    container_name: cpr-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27037:27037"

  mongo2:
    image: mongo:5.0.6
    command: mongod --port 27038
    container_name: cpr-mongo2
    restart: unless-stopped
    volumes:
      - ./db2:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27038:27038"
  
  mongo3:
    image: mongo:5.0.6
    command: mongod --port 27039
    container_name: cpr-mongo3
    restart: unless-stopped
    volumes:
      - ./db3:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27039:27039"

  mongo4:
    image: mongo:5.0.6
    command: mongod --port 27040
    container_name: cpr-mongo4
    restart: unless-stopped
    volumes:
      - ./db4:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27040:27040"

  mongo5:
    image: mongo:5.0.6
    command: mongod --port 27041
    container_name: cpr-mongo5
    restart: unless-stopped
    volumes:
      - ./db5:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27041:27041"

  nginx:
    image: nginx:1.21.6
    restart: unless-stopped
    container_name: cpr-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
      - "13125:80"